### ISSUE TITLE
Extend OpenAPISpecGeneratorPlugin to include default values for parameters

### ISSUE THREAD

**Issue by garrytrinder** [dotnet/dev-proxy#1110]
Azure API endpoints use the `api-version` query string parameter to version endpoints.

When using Dev Proxy to generate an OpenAPI spec the `api-version` parameter in not included in the generated document. This leads to an error when issuing a request as the `api-version` parameter is not sent.

We should look to include this as a parameter in generated documents with a default value.

```yaml
      parameters:
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: "2024-11-01-preview"
```
